### ISSUE TITLE
Can't open cargo disposal windoor

### ISSUE THREAD

**Issue by Ed640** [TaleStation/TaleStation#3965]
Reporting client version: 514.1585

## Round ID:
141

## Reproduction:
![image](https://user-images.githubusercontent.com/16868239/210895474-15a16f35-2b3f-46fb-af7d-9fe62fe0b208.png)
Despite being a cargo tech, unable to open the windoor.

**Comment by Jolly-66** [comment]
I know whats causing this, this is mostly due to the server not being updated, as annoying as it is.

This should be fixed by the next time we play/
