### ISSUE TITLE
The pain of pain medication.

### ISSUE THREAD

**Issue by axelzonvolt** [TaleStation/TaleStation#3968]
## Round ID:

Round ID not applicable. date discovered 01/05/2023

## Testmerges:
not applicable I believe.

## Reproduction:
Spawn in as medcial doctor and receive the pain medication paper for melbert's pain system content. 

Pick the easiest sounding one out of the list, then realize the new catalyst isn't reacting and you cannot make propinoic acid according to the paper you were given.

![painkillerbugs](https://user-images.githubusercontent.com/98575308/210903988-7dfa86a4-75d4-4fa5-9493-efa7ec8b443f.jpg)

**Comment by Jolly-66** [comment]
```
/datum/chemical_reaction/propionic_acid
	results = list(/datum/reagent/propionic_acid = 3)
	required_reagents = list(/datum/reagent/carbon = 1, /datum/reagent/oxygen = 1, /datum/reagent/hydrogen = 1)
	required_catalysts = list(/datum/reagent/toxin/acid = 1)
	is_cold_recipe = TRUE
	required_temp = 250
	optimal_temp = 200
	overheat_temp = 50
	reaction_tags = REACTION_TAG_EASY | REACTION_TAG_CHEMICAL
```

I forgot to mention the fact you need to heat it.
