### ISSUE TITLE
You can't dismember people

### ISSUE THREAD

**Issue by Jolly-66** [TaleStation/TaleStation#4056]
Giga "FUCK" moment. I have an idea of whats going on.

`code\modules\surgery\bodyparts\dismemberment.dm`, lines 24 and/or 91

**Comment by JohnFulpWillard** [comment]
downstream moment

**Comment by JohnFulpWillard** [comment]
code\modules\surgery\bodyparts\dismemberment.dm, lines 24 and/or 91

what does this mean

**Comment by Jolly-66** [comment]
> code\modules\surgery\bodyparts\dismemberment.dm, lines 24 and/or 91
> 
> what does this mean

I don't know whats causing this, this file has modular edits to it but through testing this is incorrect.

**Comment by Jolly-66** [comment]
Everything about this bug can go rot in fucking hell

**Comment by Jolly-66** [comment]
I want to believe this was caused because I added stamina back to limbs. Should test with my TG local, otherwise I'm running out of ideas.
