### ISSUE TITLE
The Books that Direct to a Wiki, the Tutorial Ones, don't seem to work.

### ISSUE THREAD

**Issue by UnionsCap** [TaleStation/TaleStation#5630]
Seems to be that the Tutorial Books don't link to anything, only checked the Space Law and Bar books, but I predict that other books are like this.

> ![image](https://user-images.githubusercontent.com/132617281/236325919-62a10042-13e6-4490-8fbc-b286c35714a9.png)

> ![image](https://user-images.githubusercontent.com/132617281/236326008-4b68aecf-16ec-4380-a9ac-8a3c78b45011.png)
__________________________________________________________________________________________________________________________________________
Might just be me being picky since in Tg the books are abhorrent to read anyways, but just letting you coders know, have a good shift.

**Comment by Jolly-66** [comment]
This is an upstream issue (https://github.com/tgstation/tgstation/issues/75047) but this is still a super What the Fuck moment. Probably has to do with the most recent book refactor.
