### ISSUE TITLE
Cat Surgeon Hostile NPC Cuts off tails even if you don't have one. 

### ISSUE THREAD

**Issue by UnionsCap** [TaleStation/TaleStation#5875]
Reporting client version: 514.1589

## Round ID:
196

## The Bug:
When the cat surgeon attacks and enters quarrel with you, It seems to be eager to cutoff your tail (Like the whole joke it is, the cat tail organ trade), so much so that she'll cut humans assess! Who don't have tails, well not real ones anyways. 
![image](https://github.com/TaleStation/TaleStation/assets/132617281/04cbf9a6-fbca-4773-a737-d38357f531a7)
![image](https://github.com/TaleStation/TaleStation/assets/132617281/27486b3d-3be5-4526-8c40-34f6caae46f6)
![image](https://github.com/TaleStation/TaleStation/assets/132617281/1358f0e7-e9bf-466d-8e29-24d0181fbe09)

A relative non-issue since the enemy is relatively uncommon, but I'm worried that this is the game mis-checking if humans have tails, being an option within the character preference menu. (_I don't want to have to attach a cat tail so that I can have balance!_)

**Comment by Jolly-66** [comment]
This is, funnily enough, a /tg/ issue. I've opened an issue up there.

**Comment by BlueMemesauce** [comment]
According to Mr Melberts comment, this isn't a tg issue
>It's because we do tailless felinids in the stupidest way - by just making the icon invisible

It's two separate issues. The tg issue is that felinids with the no tail pref actually have invisible tails. The other issue is only on this repo where humans have butts that are classified as tails.
