### ISSUE TITLE
Alternatively click functionality is broken

### ISSUE THREAD

**Issue by Jolly-66** [TaleStation/TaleStation#6405]
What the fuck happened?

Don't know where this went wrong.

Alt clicking money out of IDs is broken too.

**Comment by DATA-xPUNGED** [comment]
The menu that let's you:
Take money out of an ID
Take Many items of the same type on produce storage
Take a certain amount of items out of a stack
It is not working, i think it's the root cause of this

**Comment by Jolly-66** [comment]
#6817
